config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]
  resources :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many  :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many   :playlist_songs
  has_many   :playlists, through: :playlist_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
def index
  @artists = Artist.all
end

def new
  @artist = Artist.new
end

def create
  @artist = Artist.new(artist_params)
  if @artist.save
    redirect_to artist_path(@artist)
  else
    render :new
  end
end

def show
  @artist = Artist.find(params[:id])
end

def edit
  @artist = Artist.find(params[:id])
end

def update
  @artist = Artist.find(params[:id])
  if @artist.update(artist_params)
    redirect_to artist_path(@artist)
  else
    render :edit
  end
end

def destroy
  @artist = Artist.find(params[:id])
  @artist.destroy
  redirect_to artists_path
end

private

def artist_params
  params.require(:artist).permit(:name, :image_path)
end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
    @songs = Song.all
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def edit
    @playlist = Playlist.find(params[:id])
    @songs = Song.all
  end

  def update
    @playlist = Playlist.find(params[:id])
    if @playlist.update(playlist_params)
      redirect_to playlist_path(@playlist)
    else
      render :edit
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :image_path %>
  <%= f.text_field :image_path %>
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render partial: "shared/errors", locals: {target: @artist}%>
<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>
<%= link_to "New Artist", new_artist_path %><br/>
<% @artists.each do |artist| %>
  <%= link_to artist.name, artist_path(artist) %><br/>
<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render partial: "shared/errors", locals: {target: @artist}%>
<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<%= link_to "Edit", edit_artist_path(@artist) %><br/>
<%= link_to "Delete", artist_path(@artist), method: :delete %><br/>
<%= link_to "New Song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <% @songs.each do |song| -%>
    <div>
      <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>
<%= render partial: "shared/errors", locals: {target: @playlist}%>
<%= render partial: "form" %>

app/views/playlists/index.html.erb
<%= link_to "New Playlist", new_playlist_path %>
<% @playlists.each do |playlist| %>
  <%= link_to playlist.name, playlist_path(playlist) %>
<% end %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>
<%= render partial: "shared/errors", locals: {target: @playlist}%>
<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>
<ul>
<% @playlist.songs.each do |song| %>
  <li><%= link_to song.title, song_path(song) %>
<% end %>
</ul><br/>
<%= link_to "Edit", edit_playlist_path(@playlist) %>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
  <%= link_to @song.artist.name, artist_path(@song.artist) %>